name: 'Flutter template'
description: 'Greet someone'
inputs:
  run-test:
    description: 'Whether to run flutter test (default true)'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.8.1'
        channel: 'stable'
        cache: true
    - run: flutter test
      shell: bash
      if: ${{ inputs.run-test == 'true' }}
